from __future__ import annotations

import base64
import binascii
import io
from pathlib import Path
from typing import Any

import torch
from PIL import Image, UnidentifiedImageError

from app.labels import DOODLE_LABELS
from app.model import MobileNetV1


class DoodlePredictor:
    def __init__(self, checkpoint_path: Path) -> None:
        self.checkpoint_path = checkpoint_path
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model = MobileNetV1(ch_in=3, n_classes=len(DOODLE_LABELS)).to(self.device)
        self.loaded = False
        self.error: str | None = None

    def load(self) -> None:
        try:
            # The checkpoint is generated by the trusted local j-doodle project.
            checkpoint = torch.load(self.checkpoint_path, map_location=self.device, weights_only=False)
            state_dict = checkpoint.get("model_state_dict", checkpoint) if isinstance(checkpoint, dict) else checkpoint
            state_dict = {
                key.removeprefix("module."): value
                for key, value in state_dict.items()
            }
            self.model.load_state_dict(state_dict)
            self.model.eval()
            self.loaded = True
            self.error = None
        except Exception as exc:  # pragma: no cover - reported by health endpoint.
            self.loaded = False
            self.error = str(exc)

    def predict(self, image_base64: str, top_k: int = 3) -> dict[str, Any]:
        if not self.loaded:
            raise RuntimeError(self.error or "MODEL_NOT_LOADED")

        tensor = self._preprocess(image_base64)
        with torch.inference_mode():
            logits = self.model(tensor)
            probabilities = torch.softmax(logits, dim=1)[0]
            k = max(1, min(top_k, len(DOODLE_LABELS)))
            scores, indexes = torch.topk(probabilities, k=k)

        predictions = []
        for score, index in zip(scores.tolist(), indexes.tolist(), strict=True):
            label = DOODLE_LABELS[index]
            predictions.append(
                {
                    "class_key": label["class_key"],
                    "english": label["english"],
                    "vi": label["vi"],
                    "phonetic": label["phonetic"],
                    "confidence": round(float(score), 4),
                }
            )

        return {
            "predicted_class": predictions[0]["class_key"],
            "confidence": predictions[0]["confidence"],
            "top_predictions": predictions,
        }

    def _preprocess(self, image_base64: str) -> torch.Tensor:
        if "," in image_base64 and image_base64.split(",", 1)[0].startswith("data:image"):
            image_base64 = image_base64.split(",", 1)[1]

        try:
            image_bytes = base64.b64decode(image_base64, validate=True)
        except (binascii.Error, ValueError) as exc:
            raise ValueError("INVALID_IMAGE_BASE64") from exc

        try:
            image = Image.open(io.BytesIO(image_bytes))
        except UnidentifiedImageError as exc:
            raise ValueError("INVALID_IMAGE_FILE") from exc

        if image.mode == "RGBA":
            background = Image.new("RGBA", image.size, (255, 255, 255, 255))
            background.alpha_composite(image)
            image = background.convert("RGB")
        else:
            image = image.convert("RGB")

        image = image.resize((224, 224), Image.Resampling.BILINEAR)
        byte_tensor = torch.ByteTensor(torch.ByteStorage.from_buffer(image.tobytes()))
        tensor = byte_tensor.view(224, 224, 3).permute(2, 0, 1).float().div(255.0)
        tensor = tensor.sub(0.5).div(0.5)
        return tensor.unsqueeze(0).to(self.device)
